config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :users do
    get '/users', to: redirect("/users/sign_up")
  end
  get 'events/index'
  root to: 'events#index'
  resources :events do
    member do
      put 'done'
    end
  end
  post 'users/guest_sign_in', to: 'users#new_guest'
  # put 'events/todo_done', to: 'events#done'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '予定' },
    { id: 2, name: 'Todo' },
    { id: 3, name: '完了済Todo'}
  ]
  end

app/models/event.rb
class Event < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :events

  with_options presence: true do
    validates :nick_name
    validates :password, length: { minimum: 6 }, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
  end

  def self.guest
    find_or_create_by!(nick_name: 'ゲスト', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :gon_set, only: [:index, :new, :edit]
before_action :move_to_index, except: [:index]
before_action :set_event, only: [:edit, :update, :destroy, :done]
before_action :user_check, only: [:edit, :update, :destroy, :done]

  def index
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.valid?
      @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    if @event.destroy
      redirect_to root_path
    end
  end

  def done
    @event.category_id = 3
    if @event.save
      flash[:notice] = "【#{@event.title}】完了！"
      redirect_to root_path
    end
  end


  private

  def event_params
    params.require(:event).permit(:title, :detail, :event_date, :event_time, :category_id).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to new_user_session_path unless user_signed_in?
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def user_check
    redirect_to root_path unless current_user.id == @event.user_id
  end

  def gon_set
    if user_signed_in?
      @events = Event.where(user_id: current_user.id).order(event_date: :asc)
    else
      @events = Event.where(user_id: 1)
    end
      gon.event = @events
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<h1>変更フォーム</h1>


<div class="Form">
  <%= form_with model: @event, local: true do |f| %>
  <%= render "shared/error_messages", model: f.object %>
  <div class="Form-Item">
      <span class="Form-Item-Label-Required">必須</span>
      イベント名
      <div class="form-content">
        <%= f.text_area :title, class:"events-text", id:"event-name", placeholder:"イベント名（20字以内）", maxlength:"20" %>
      </div>
  </div>
  <div class="Form-Item">
    <span class="Form-Item-Label-Any">任意</span>
      イベント内容
      <div class="form-content">
        <%= f.text_area :detail, class:"events-text", id:"event-info", placeholder:"内容（100字以内）" ,rows:"7" ,maxlength:"100" %>
      </div>
   </div>
  <div class="Form-Item">
    <span class="Form-Item-Label-Required">選択</span>
    予定 or Todo
    <label class="plan"><%= f.radio_button :category_id, 1, checked: true%>予定</label>
    <label class="todo"><%= f.radio_button :category_id, 2 %>Todo</label>
  </div>
  <div class="Form-Item">
    <span class="Form-Item-Label-Required">必須</span>
    日付
    <div class="form-content">
      <%= raw sprintf(
        f.date_field(
          :event_date,
                      date_separator: '%s'),
                    "<p> 年 </p>", "<p> 月 </p>") + "<p>  </p>" %>
    </div>
  </div>
  <div class="Form-Item">
    <span class="Form-Item-Label-Any">任意</span>
    時間
    <div class="form-content">
      <%= f.time_field :event_time, class: 'form-control', include_blank: true%>
    </div>
  </div>
  <div>
    <%= f.submit "入力完了" ,class:"Form-Btn" %>
  </div>
  <% end %>
  
</div>

<div class="mini-calendar-box">
  <table class="mini-calendar">
    <thead>
      <tr>
        <th id="prev">&laquo;</th>
        <th id="title" colspan="5">2020/05</th>
        <th id="next">&raquo;</th>
      </tr>
      <tr>
        <th>Sun</th>
        <th>Mon</th>
        <th>Tue</th>
        <th>Wed</th>
        <th>Thu</th>
        <th>Fri</th>
        <th>Sat</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
      <tr>
        <td id="today" colspan="7">Today</td>
      </tr>
    </tfoot>
  </table>
</div>

<a href= "/" >
  <div class='purchase-btn'>
    <span class='purchase-btn-text'><br>戻る</span>
    <%= image_tag 'calendar.png' , size: '185x75' ,class: "purchase-btn-icon" %>
  </div>
</a>

app/views/events/index.html.erb
<%= render "shared/header" %>
<div class="todo-countdown-title">
  <p>You have to do it!</p>
</div>
<div class="notice-zone">
  <p class="notice">
  <%=  notice %> 
  </p>
</div>
<% d = Date.today%>
<div class="countdown">
  <div class="todo-countdown">
    <% @events.each do |event| %>
      <% if event.category_id == 2 && d <= event.event_date %>
        <% cut_day = "#{event.event_date - d}" %>
        <% cut_day_num = cut_day.length - 2%>
        <% last_day = cut_day.slice(0, cut_day_num).to_i %>
        <% if last_day <= 3 %>
          <div class="countdown-zone-red" id="box_todo_id_<%= event.id %>" >
            <div class="countdown-zone-date">
              <%= "残り #{last_day} 日！"%>
            </div>
            <div class="countdown-zone-title">
              <%= event.title %>
            </div>
            <div class="done-box" id="todo_id_<%= event.id %>">
              <div class="done-zone">
                <%= link_to 'done!', done_event_path(event.id), method: :put %>
              </div>
            </div>
          </div>
        <% elsif last_day <= 7 %>
          <div class="countdown-zone-yellow">
            <div class="countdown-zone-date">
              <%= "残り #{last_day} 日！"%>
            </div>
            <div class="countdown-zone-title">
              <%= event.title %>
            </div>
            <div class="done-box" id="todo_id_<%= event.id %>">
              <div class="done-zone">
                <%= link_to 'done!', done_event_path(event.id), method: :put %>
              </div>
            </div>
          </div>
        <% elsif last_day <= 14 %>
          <div class="countdown-zone-blue">
            <div class="countdown-zone-date">
              <%= "残り #{last_day} 日！"%>
            </div>
            <div class="countdown-zone-title">
              <%= event.title %>
            </div>
            <div class="done-box" id="todo_id_<%= event.id %>">
              <div class="done-zone">
                <%= link_to 'done!', done_event_path(event.id), method: :put %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th id="prev">&laquo;</th>
      <th id="title" colspan="5">2020/05</th>
      <th id="next">&raquo;</th>
    </tr>
    <tr>
      <th>Sun</th>
      <th>Mon</th>
      <th>Tue</th>
      <th>Wed</th>
      <th>Thu</th>
      <th>Fri</th>
      <th>Sat</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
  <tfoot>
    <tr>
      <td id="today" colspan="7">Today</td>
    </tr>
  </tfoot>
</table>


<div class="list-box">
  <div class="plan-list">
    <h1>予定一覧</h1>
    <ul class="plans">
      <% @events.each do |event| %>
        <% if event.category_id == 1 && d <= event.event_date %>
          <li class="a-plan">
            <div class="date-title-zone">
              <div class="date-zone">
                <%= event.event_date %>
              </div>
              <div class="title-zone">
                <%= event.title %>
              </div>
            </div>
            <div class="show-edit-delete-zone">
              <div class="show-zone">
                <label for="label<%= event.id %>">詳細</label>
                <input type="checkbox" id="label<%= event.id %>">
                <div class="show-hidden-zone-plan" style="z-index:2" >
                  <%= event.title %><br>
                  日付：<%= event.event_date %><br>
                  <% if event.event_time %>
                    <% t = "#{event.event_time}" %>
                    <% time = t.slice(11..15) %>
                    時間：<%= time %><BR>
                  <% else %>
                    時間：未設定<br>
                  <% end %>
                  <% unless event.detail == "" %>
                    内容：<%= event.detail %><br>
                  <% else %>
                    内容：未設定<br>
                  <% end %>
                  ※再度ボタンをクリックすると閉じます
                </div>
              </div>
              <div class="edit-zone">
                <%= link_to '変更', edit_event_path(event.id), method: :get %>
              </div>
              <div class="delete-zone">
                <%= link_to '削除', event_path(event.id), method: :delete %>
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div class="todo-list">
    <h1>todo一覧</h1>
    <ul class="todos">
      <% @events.each do |event| %>
        <% if event.category_id >= 2 && d <= event.event_date %>
          <li class="a-todo">
            <div class="date-title-zone">
              <div class="date-zone">
                <%= event.event_date %>
              </div>
              <div class="title-zone">
                <%= event.title %>
              </div>
            </div>
            <div class="show-edit-delete-zone">
              <div class="show-zone">
                <label for="label<%= event.id %>">詳細</label>
                <input type="checkbox" id="label<%= event.id %>">
                <div class="show-hidden-zone-todo" style="z-index:2" >
                  <%= event.title %><br>
                  日付：<%= event.event_date %><br>
                  <% if event.event_time %>
                    <% t = "#{event.event_time}" %>
                    <% time = t.slice(11..15) %>
                    時間：<%= time %><BR>
                  <% else %>
                    時間：設定されていません<br>
                  <% end %>
                  <% unless event.detail == "" %>
                    内容：<%= event.detail %><br>
                  <% else %>
                    内容：設定されていません<br>
                  <% end %>
                  ※再度ボタンをクリックすると閉じます
                </div>
              </div>
              <div class="edit-zone">
                <%= link_to '変更', edit_event_path(event.id), method: :get %>
              </div>
              <div class="delete-zone">
                <%= link_to '削除', event_path(event.id), method: :delete %>
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
  </div>
</div>

<div class="help-box">
</div>

<footer>
  <div class="about-app">
    <div class="explain-border">
      <div class="explain-title">
        <h1>マイのスケについて ~About MyScheduleBook~</h1>
      </div>
      <ul class="app-explains">
        <li class="explain">
          <span class="explain-head">１．アプリ利用について</span><br>
          このアプリの利用にはユーザー登録が必要です。<br>
          <%= link_to 'こちら', new_user_registration_path %>から登録できます。登録済みの方は<%= link_to 'こちら', new_user_session_path %>からログインしてください。<br>
          ※ページ上部にあるボタンからでも新規登録・ログインできます。<br>
          （ゲストログインでは登録の必要なく、それぞれの機能をお試し頂けます。）
        </li>
        <li class="explain">
          <span class="explain-head">２．イベント（予定やtodo）作成について</span><br>
          右下の「イベント作成ボタン」から予定やtodoの登録を行ってください。<br>
          登録されたイベント名や時間（設定時）がカレンダーに表示されます。<br>
          また、前月や次月の日付欄にも該当イベントがある場合、それぞれ表示されますが、<br>
          年をまたぐ場合（12月〜1月）のみ表示されないのでご注意ください。
        </li>
        <li class="explain">
          <span class="explain-head">3．イベント（予定やtodo）一覧表示について</span><br>
          日付が本日以降のもの（当日含む）のみ、日付が近い順に表示されます。<br>
          「詳細」ボタンを押すと、内容や時間の確認ができます。<br>
          「編集」ボタンを押すと、編集ページに遷移します。<br>
          「削除」ボタンを押すと、登録したイベントが削除されます。
        </li>
        <li class="explain">
          <span class="explain-head">４．「You have to do it!」について</span><br>
          「todo」を作成した場合、期限が近づくとtodoリストが表示されます。<br>
          期限が近いものから表示され、残り日数によって背景が変化します。<br>
          <span class="red">&nbsp;赤…残り３日以内&nbsp;</span> &emsp; <span class="yellow">&nbsp;黄…残り７日以内&nbsp;</span> &emsp; <span class="blue">&nbsp;青…残り１４日以内&nbsp;</span><br>
          リスト内の「Done!」ボタンを押すことで、リストから削除することができますが<br>
          カレンダーやカレンダー下部のtodo一覧には残るようにしております。<br>
          完全に削除したい場合は、カレンダー下部のtodo一覧の削除ボタンより消してください。
        </li>
      </ul>
    </div>
</footer>
  <a href="events/new">
    <div class='purchase-btn'>
    <span class='purchase-btn-text'><br>イベント作成</span>
    <%= image_tag 'pencil.png' , size: '185x75' ,class: "purchase-btn-icon" %>
    </div>
  </a>

app/views/events/new.html.erb
<h1>入力フォーム</h1>


<div class="Form">
  <%= form_with model: @event, local: true do |f| %>
  <%= render "shared/error_messages", model: f.object %>
  <div class="Form-Item">
      <span class="Form-Item-Label-Required">必須</span>
      イベント名
      <div class="form-content">
        <%= f.text_area :title, class:"events-text", id:"event-name", placeholder:"イベント名（20字以内）", maxlength:"20" %>
      </div>
  </div>
  <div class="Form-Item">
    <span class="Form-Item-Label-Any">任意</span>
      イベント内容
      <div class="form-content">
        <%= f.text_area :detail, class:"events-text", id:"event-info", placeholder:"内容（100字以内）" ,rows:"7" ,maxlength:"100" %>
      </div>
   </div>
  <div class="Form-Item">
    <span class="Form-Item-Label-Required">選択</span>
    予定 or Todo
    <label class="plan"><%= f.radio_button :category_id, 1, checked: true%>予定</label>
    <label class="todo"><%= f.radio_button :category_id, 2 %>Todo</label>
  </div>
  <div class="Form-Item">
    <span class="Form-Item-Label-Required">必須</span>
    日付
    <div class="form-content">
      <%= raw sprintf(
        f.date_field(
          :event_date,
                      value: Time.now.strftime("%Y-%m-%d"),
                      date_separator: '%s'),
                    "<p> 年 </p>", "<p> 月 </p>") + "<p>  </p>" %>
    </div>
  </div>
  <div class="Form-Item">
    <span class="Form-Item-Label-Any">任意</span>
    時間
    <div class="form-content">
      <%= f.time_field :event_time, class: 'form-control', include_blank: true%>
    </div>
  </div>
  <div>
    <%= f.submit "入力完了" ,class:"Form-Btn" %>
  </div>
  <% end %>
  

</div>
<div class="mini-calendar-box">
  <table class="mini-calendar">
    <thead>
      <tr>
        <th id="prev">&laquo;</th>
        <th id="title" colspan="5">2020/05</th>
        <th id="next">&raquo;</th>
      </tr>
      <tr>
        <th>Sun</th>
        <th>Mon</th>
        <th>Tue</th>
        <th>Wed</th>
        <th>Thu</th>
        <th>Fri</th>
        <th>Sat</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
      <tr>
        <td id="today" colspan="7">Today</td>
      </tr>
    </tfoot>
  </table>
</div>

<a href= "/" >
  <div class='purchase-btn'>
    <span class='purchase-btn-text'><br>戻る</span>
    <%= image_tag 'calendar.png' , size: '185x75' ,class: "purchase-btn-icon" %>
  </div>
</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>マイのスケ~MSB~</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= Gon::Base.render_data %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="top-content">
    <ul class="title-content">
      <li class="main-title">マイのスケ ~MyScheduleBook~ </li>
      <li class="sub-title">予定とtodoをまとめて管理</li>
    </ul>
    <ul class='login-content'>
      <% if user_signed_in? %>
        <div class="login-now-content">
          <li class="user-box"><%= link_to current_user.nick_name, "#", class: "user-nickname" %></li>
          <li class="user-box"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout"%></li> 
        </div>
      <% else %>
        <div class="guest-content">
          <li class="user-box"><%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: "login"%></li>
        </div>
        <div class="not-login-content">
          <li class="user-box"><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
          <li class="user-box"><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
        </div>
      <% end %>      
    </ul>
  </div>
</header>